# Copyright (c) Microsoft. All rights reserved.
#  Licensed under the MIT license.
name: mlflow-example
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - mlflow
    - azureml-mlflow