name: mlops-mlflow-local
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
    - azureml-sdk
    - mlflow
    - azureml-mlflow
    - azureml-opendatasets
    - pandas==1.3.5
    - scikit-learn==1.0.2
